name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UV_VERSION: "0.6.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
      - uses: actions/checkout@v4

      - &install_deps
        name: Install dependencies
        run: |
          pip install uv==${{ env.UV_VERSION }}
          uv sync

      - name: Format check
        run: uv run ruff format --check

      - name: Lint check
        run: uv run ruff check

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim

    steps:
      - uses: actions/checkout@v4
      - *install_deps

      - name: Run tests
        run: uv run pytest

  release:
    if: github.ref == 'refs/heads/main'
    needs: [lint]  # TODO когда появятся тесты включить сюда
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest